### ISSUE TITLE
Use 'Deployment' build configuration

### ISSUE THREAD

**Issue by dmitry-treskunov** [vyadh/teamcity-deployment-dashboard#1]
TeamCity has the concept of 'Deployment' build configuration: https://www.jetbrains.com/help/teamcity/2019.1/deployment-build-configuration.html

Can it somehow be used in the plugin?

**Comment by vyadh** [comment]
Yes, and indeed that's how it works. It only shows builds that are deployments (see readme on build visibility).

I like what TeamCity does with the deployment concept, that you can see where a build has been deployed. The only problem is that quite often I want to see this at the project level, or a team level. So I built this plugin for the higher level view.

In the plugin, if you click a deployment from the dashboard, it will take you to the TeamCity build overview page, again listing all the deployments using that out of the box functionality.

Best of both worlds :)

**Comment by dmitry-treskunov** [comment]
Cool, thank you! Awesome plugin!

**Comment by vyadh** [comment]
Thanks Dmitry!
