### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by bankinobi** [vyadh/teamcity-deployment-dashboard#2]
Hello Vyadh!
Trying to set up your awesome plugin, but i'm stuck.
I have a project with below settings:
![Selection_011](https://user-images.githubusercontent.com/28591219/59919151-c0c8ad80-9437-11e9-85b0-c0bb52fc3245.png)
I want to see a branch name on dashboard. So after deploying master branch i tried to deploy tagged branch 1.0.2
![Selection_007](https://user-images.githubusercontent.com/28591219/59919186-d63dd780-9437-11e9-9731-12941f748189.png)
Branch name appears on dashboard while it was deploying
![Selection_009](https://user-images.githubusercontent.com/28591219/59919187-d63dd780-9437-11e9-9484-6dc20875c7ee.png)
But after deploy branch name on dashboard changed to "master" again
![Selection_010](https://user-images.githubusercontent.com/28591219/59919188-d6d66e00-9437-11e9-964a-b0b9c0e8be4c.png)
What i'm doing wrong?

**Comment by vyadh** [comment]
Hi Bankinobi. Thanks for the feedback and the great bug report. I think understand why this is happening. The plugin first fetches the last running build and displays that, but if there isn't a running build, it queries the "last changes finished" build, which I thought just got the last run build, but given your query and having another look, I found a note that said it actually takes the build from default branch. So I'm guessing your master is your default branch right?

So given what we need to do on the dashboard, the function I'm using clearly isn't quite right. I've found an alternative. It's slightly more involved (need to process the build history), but I'll get that sorted over the weekend.

Thanks for pointing this out!

**Comment by vyadh** [comment]
Okay, I've fixed the problem as above by using an alternative / lower-level way of querying the build history. The dashboard should now always reflect the most recent version deployed no matter what branch was used. Thanks for pointing this out.

You should be able to see this update available from TeamCity. The release notes are [here](https://github.com/vyadh/teamcity-deployment-dashboard/releases/tag/v1.2.0) which also has a few other minor changes.

Let me know if you have further problems, either by reopening this issue or by opening a new one.

**Comment by bankinobi** [comment]
Works like a charm. Thank you!
![Selection_013](https://user-images.githubusercontent.com/28591219/59974878-2779d280-95c2-11e9-87f6-aa294a36ede5.png)
