### ISSUE TITLE
Support displaying branch information

### ISSUE THREAD

**Issue by brimimc** [vyadh/teamcity-deployment-dashboard#21]
And take into account branch when deciding which build is old (i.e. the latest change on develop branch should show up as latest even if there is a feature branch build that is newer deployed to a different env

**Comment by brimimc** [comment]
I'd like to be able to scan the environments in the dashboard and know which feature branch is deployed where. Today I have to click on each build to see which branch it is and then see if there are any newer builds for that branch - it's a lot of clicks

**Comment by vyadh** [comment]
Good idea to show the branch. Not a huge amount of space available though. Maybe if is optional, and is truncated if the name is too long it might work...

As to the point about taking into account the branch. Can you explain a bit more what you mean? Currently, it doesn't matter what branch it's on, it's the environment and time of deployment that is important.

**Comment by brimimc** [comment]
So currently it seems that when deciding which builds are considered old, if I have the latest master branch deployed to PROD env, but there is a later develop branch deployed to QA, the PROD env build is considered old. Same in the case where I have a feature branch build deployed to QA1 env, even though I have the latest develop branch build deployed to QA2, it shows as old because the feature branch was built and deployed more recently. 

The issue I have is that all but one deployment is showing as old when it really depends on what you mean by old. I think it should be branch specific so it should only show as old if there is a newer build on that branch ready to be deployed. I realize that it probably not in the scope of what the dashboard knows (it only knows about deployments).

The most important thing is being able to see the branch name. Deciding which build are old is probably more user specific.

**Comment by vyadh** [comment]
This has been added in v1.10.0 via the custom property feature.
