### ISSUE TITLE
The last/latest build's version is not being used when two different build configs (master and branch) deploy to the same environment

### ISSUE THREAD

**Issue by wizardshill** [vyadh/teamcity-deployment-dashboard#7]
The majority of my projects use two build configs (master and branch) that deploy to the same environments.
The Master build config is used for normal release cycle deployments.
The Branch build config is used primary for hotfix release cycle deployments.

Both build configs deploy to:
  project = A
  environment = TEST

It seems this plugin displays the first, or last, version it finds, for each project-environment.
It should display the most recent deployment according to the build date.

If the last build of Master was deployed yesterday and the last build of Branch was deployed this morning...
The Plugin should display the Branch's version info.

If the last build of Master was deployed yesterday and last build of Branch was deployed last month...
The Plugin should display the Master's version info.

**Comment by vyadh** [comment]
That's an interesting case... Yes, you're absolutely right, if there are multiple project/environment deployments, only one is displayed. The frontend dashboard uses the first, but ordering coming from the backend probably depends on the ordering of the configurations in the TeamCity API we're using.

I'm just adding a duplicate resolver step which does at you suggest. It groups by project/environment and then keeps the one with the latest date. Once I'm done I'll post a new version to JetBrain's plugin repo.

**Comment by vyadh** [comment]
That's now done. Please update and let me know if this fixes the problem.

Thanks for reporting.

**Comment by wizardshill** [comment]
That seems to have fixed it.
Thanks for the quick turnaround.
This is a pretty cool plugin!

**Comment by wizardshill** [comment]
What is the significants between the bright and faded icons?
There seems to be no rhyme or reason for it.
