### ISSUE TITLE
Date/Time

### ISSUE THREAD

**Issue by wizardshill** [vyadh/teamcity-deployment-dashboard#9]
Some deployments show the date and others just show the time.
Looks like a bug of some short
![Screen Shot 2019-07-12 at 9 52 37 AM](https://user-images.githubusercontent.com/9683200/61144936-1c141b80-a48b-11e9-99b8-e854de0b3908.png)

**Comment by vyadh** [comment]
This is actually intentional as per the readme:

> Shows deployment time or the date if not today.

This is mainly because there isn't space show both. I did wonder whether I should provide a tooltip or something that showed the date and time so there was no ambiguity...

**Comment by vyadh** [comment]
I'll close this as it's intended behaviour, but feel free to let me know your thoughts...

**Comment by wizardshill** [comment]
Thanks, that didn't occur to me... it was something I just realized when creating the other tickets and when ahead and created this as well
